// Game types — plain numbers, no ICP bigint dependency

export interface Pos { x: number; y: number }
export type UnitId = number;

export enum TerrainKind {
  grass    = 'grass',
  water    = 'water',
  forest   = 'forest',
  mountain = 'mountain',
}

export enum PlayerTag {
  blue = 'blue',
  red  = 'red',
}

export enum UnitKind {
  swordsman = 'swordsman',
  pikeman   = 'pikeman',
  pillager  = 'pillager',
  archer    = 'archer',
  knight    = 'knight',
  brute     = 'brute',
  catapult  = 'catapult',
}

export enum UnitArchetype {
  infantry       = 'infantry',
  antiCavalry    = 'antiCavalry',
  scout          = 'scout',
  cavalry        = 'cavalry',
  rangedInfantry = 'rangedInfantry',
  siege          = 'siege',
  heavyInfantry  = 'heavyInfantry',
}

export enum StructureKind {
  castle     = 'castle',
  settlement = 'settlement',
  mine       = 'mine',
  barricade  = 'barricade',
}

export enum GameError {
  unitNotFound       = 'unitNotFound',
  unitAlreadyMoved   = 'unitAlreadyMoved',
  unitAlreadyAttacked= 'unitAlreadyAttacked',
  invalidTarget      = 'invalidTarget',
  outOfRange         = 'outOfRange',
  impassableTerrain  = 'impassableTerrain',
  gameOver           = 'gameOver',
  notEnoughGold      = 'notEnoughGold',
  invalidUnitKind    = 'invalidUnitKind',
}

export type GameStatus =
  | { __kind__: 'active'; active: null }
  | { __kind__: 'won'; won: PlayerTag };

export interface Tile { pos: Pos; terrain: TerrainKind }

export interface UnitView {
  id: UnitId;
  owner: PlayerTag;
  kind: UnitKind;
  archetype: UnitArchetype;
  strength: number;
  moveRange: number;
  attackRangeMin: number;
  attackRangeMax: number;
  killGold: number;
  pos: Pos;
  hp: number;
  maxHp: number;
  moved: boolean;
  attacked: boolean;
}

export interface CastleView {
  owner: PlayerTag;
  pos: Pos;
  hp: number;
  maxHp: number;
  /** Lifetime gold generated by this castle (max 500). */
  goldGenerated: number;
}

export interface StructureView {
  id: string;
  kind: StructureKind;
  pos: Pos;
  owner?: number;
  hp: number;
  maxHp: number;
  /** Lifetime gold generated by this mine (max 1,000). */
  goldGenerated: number;
}

export interface MatchStateView {
  tiles: Tile[];
  units: UnitView[];
  castles: CastleView[];
  structures: StructureView[];
  playerGold: Array<[number, number]>;
  tickCount: number;
  lastTickTime: number;
  status: GameStatus;
  mapSeed: number;
  playerCount: number;
}

export type ActionResult<T = null> =
  | { success: true; data: T }
  | { success: false; error: GameError | string };

export function parsePlayerGold(raw: Array<[number, number]>): Record<number, number> {
  const map: Record<number, number> = {};
  for (const [idx, gold] of raw) map[idx] = gold;
  return map;
}
