export type TerrainKind = 'grass' | 'water' | 'forest' | 'mountain';
export type PlayerTag = 'blue' | 'red';
export type UnitKind = 'swordsman' | 'pikeman' | 'pillager' | 'archer' | 'knight' | 'brute' | 'catapult';
export type UnitArchetype = 'infantry' | 'antiCavalry' | 'scout' | 'cavalry' | 'rangedInfantry' | 'siege' | 'heavyInfantry';
export type StructureKind = 'castle' | 'settlement' | 'mine' | 'barricade';
export type GameStatus = { __kind__: 'active'; active: null } | { __kind__: 'won'; won: PlayerTag };

export type GameError =
  | 'unitNotFound'
  | 'unitAlreadyMoved'
  | 'unitAlreadyAttacked'
  | 'invalidTarget'
  | 'outOfRange'
  | 'impassableTerrain'
  | 'gameOver'
  | 'notEnoughGold'
  | 'invalidUnitKind';

export interface Pos { x: number; y: number }

export interface UnitStats {
  cost: number;
  maxHp: number;
  strength: number;
  moveRange: number;
  attackRangeMin: number;
  attackRangeMax: number;
  killGold: number;
  archetype: UnitArchetype;
}

export interface Unit {
  id: number;
  owner: PlayerTag;
  kind: UnitKind;
  archetype: UnitArchetype;
  strength: number;
  moveRange: number;
  attackRangeMin: number;
  attackRangeMax: number;
  killGold: number;
  pos: Pos;
  hp: number;
  maxHp: number;
  moved: boolean;
  attacked: boolean;
}

export interface Castle {
  owner: PlayerTag;
  pos: Pos;
  hp: number;
  maxHp: number;
  /** Total gold generated by this castle across its lifetime (cap: 500). */
  goldGenerated: number;
}

export interface Structure {
  id: string;
  kind: StructureKind;
  pos: Pos;
  owner?: number;
  hp: number;
  maxHp: number;
  /** Total gold generated by this mine across its lifetime (cap: 1,000). Only relevant for mines. */
  goldGenerated: number;
}

export interface Tile { pos: Pos; terrain: TerrainKind }

export interface MatchState {
  id: string;
  tiles: Map<number, TerrainKind>;
  units: Map<number, Unit>;
  castles: Map<number, Castle>;
  structures: Map<string, Structure>;
  playerGold: Map<number, number>;
  nextUnitId: number;
  tickCount: number;
  lastTickTime: number;    // Unix ms — used by client for countdown display
  status: GameStatus;
  mapSeed: number;
  playerTokens: [string | null, string | null];
  playerCount: number;
  createdAt: number;
  tickIntervalId?: ReturnType<typeof setInterval>;
}

export interface MatchStateView {
  tiles: Tile[];
  units: Unit[];
  castles: Castle[];
  structures: Structure[];
  playerGold: Array<[number, number]>;
  tickCount: number;
  lastTickTime: number;
  status: GameStatus;
  mapSeed: number;
  playerCount: number;
}

export interface GameListEntry {
  id: string;
  playerCount: number;
  tickCount: number;
  status: GameStatus;
  createdAt: number;
}
